version: 2
updates:
  - package-ecosystem: 'pip'
    directories:
      - '/'
    schedule:
      interval: 'daily'
      time: '09:00'
      timezone: 'America/Los_Angeles'
    target-branch: 'develop'
    labels:
      - 'dependencies'

  - package-ecosystem: 'docker'
    directories:
      - '/resource_provisioning/airflow/docker'
      - '/resource_provisioning/mlflow/docker'
    schedule:
      interval: 'daily'
      time: '09:00'
      timezone: 'America/Los_Angeles'
    target-branch: 'develop'
    labels:
      - 'dependencies'

  - package-ecosystem: 'terraform'
    directories:
      - '/'
    schedule:
      interval: 'daily'
      time: '09:00'
      timezone: 'America/Los_Angeles'
    target-branch: 'develop'
    labels:
      - 'dependencies'

  - package-ecosystem: 'github-actions'
    directories:
      - '/.github/workflows'
    schedule:
      interval: 'daily'
      time: '09:00'
      timezone: 'America/Los_Angeles'
    target-branch: 'develop'
    labels:
      - 'dependencies'
