name: Build and Push Docker Images

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      custom_tag:
        description: 'Custom image tag'
        required: true
        default: 'develop'

jobs:
  push_to_ghcr:
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - name: airflow
            directory: airflow/docker
          - name: mlflow
            directory: mlflow/docker
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tag based on event
        id: set_tag
        run: |
            if [[ "${{ github.event_name }}" == "workflow_run" ]]; then
                echo "TAG=${{ github.event.workflow_run.outputs.new_release_version }}" >> $GITHUB_ENV
            else
                echo "TAG=${{ github.event.inputs.custom_tag }}" >> $GITHUB_ENV
            fi

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.image.name }}:${{ env.TAG }}

      - name: Build and push Docker image
        id: push_image
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.image.directory }}
          file: ./${{ matrix.image.directory }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ matrix.image.name }}:${{ env.TAG }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/${{ github.repository }}/${{ matrix.image.name }}
          subject-digest: ${{ steps.push_image.outputs.digest }}
          push-to-registry: true
